version: '3.8'

services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - neo4j_net
    volumes:
      - ./api:/api
    environment:
      - NEO4J_URL=bolt://db:7687
  client:
    build: ./client
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./client:/client
    environment:
      - REACT_APP_API_BASE_URL=http://127.0.0.1:8080
  db:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
    environment:
      - NEO4J_AUTH=none
    networks:
      - neo4j_net

networks:
  neo4j_net:
    driver: bridge
